name: "Deploy Aplicação Laravel"
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
        - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
          with:
            php-version: '8.3.12-fpm-bullseye'

        - name: Baixar o código atualizado
          uses: actions/checkout@v4

        # - name: Entrar no diretório da aplicação e lista os arquivos
        #   run: cd ./app && ls -lah

        - name: Copiar arquivo .env
          run: cd ./app && php -r "file_exists('.env') || copy('.env.example', '.env');"
        
        - name: Instalar dependências da aplicação
          run: cd ./app && composer install --no-interaction && composer require league/flysystem-aws-s3-v3 "^3.0" --with-all-dependencies
          #run: cd ./app && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

        # - name: Gerar a chave da aplicação
        #   run: php artisan key:generate
        